dist: bionic
sudo: required
language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
 # - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_script:
#  - sudo apt-get update -q
#  - sudo apt install doxygen -y
#  - sudo apt install graphviz -y

before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake -DCOVERAGE=ON .
  - cmake --build .
  
after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"

env:
  - TARGET=bulkmt
