dist: bionic
sudo: required
language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
 # - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_script:
#  - sudo apt-get update -q
  - sudo apt install doxygen -y
  - sudo apt install graphviz -y

script:
  - cmake .
  - cmake --build .

env:
  - TARGET=bulkmt
